# generate github workflow that runs linter and jest unit tests
# on every push to main branch using pnpm

name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: pnpm/action-install@v1
        with:
          version: 6
          args: install --frozen-lockfile
      - name: Lint
        run: pnpm run lint
      - name: Test
        run: pnpm run test
